name: Rails RSpec
on:
  workflow_call:
    inputs:
      node-version:
        type: string
      node-version-file:
        type: string
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          #node-version-file: ${{ inputs.node-version-file }}
          cache: "yarn"
      
      - name: Install Node packages
        run: yarn install --pure-lockfile

      - name: Setup test database
        env: 
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: bundle exec rails db:setup

      - name: Run tests (RSpec)
        run: bundle exec rspec
